export const BRANCH_LINT_CONFIG_FILE_NAMES: Array<string> = [
	".elsikora/git-branch-lint.config.js",
	`.elsikora/.git-branch-lintrc`,
	`.elsikora/.git-branch-lintrc.json`,
	`.elsikora/.git-branch-lintrc.yaml`,
	`.elsikora/.git-branch-lintrc.yml`,
	`.elsikora/.git-branch-lintrc.js`,
	`.elsikora/.git-branch-lintrc.ts`,
	`.elsikora/.git-branch-lintrc.mjs`,
	`.elsikora/.git-branch-lintrc.cjs`,
	`.elsikora/git-branch-lint.config.js`,
	`.elsikora/git-branch-lint.config.ts`,
	`.elsikora/git-branch-lint.config.mjs`,
	`.elsikora/git-branch-lint.config.cjs`,
];
