export enum EEslintFeature {
	CHECK_FILE = "checkFile",
	CSS = "css",
	JAVASCRIPT = "javascript",
	JSDOC = "jsdoc",
	JSON = "json",
	JSX = "jsx",
	MARKDOWN = "markdown",
	NEST = "nest",
	NEXT = "next",
	NODE = "node",
	PACKAGE_JSON = "packageJson",
	PERFECTIONIST = "perfectionist",
	PRETTIER = "prettier",
	REACT = "react",
	REGEXP = "regexp",
	SONAR = "sonar",
	STYLISTIC = "stylistic",
	TAILWIND_CSS = "tailwindCss",
	TYPEORM = "typeorm",
	TYPESCRIPT = "typescript",
	UNICORN = "unicorn",
	YAML = "yaml",
}
