export enum EModule {
	BRANCH_LINT = "branch-lint",
	BUILDER = "builder",
	CI = "ci",
	COMMITLINT = "commitlint",
	ESLINT = "eslint",
	GITIGNORE = "gitignore",
	IDE = "ide",
	LICENSE = "license",
	LINT_STAGED = "lint-staged",
	PRETTIER = "prettier",
	SEMANTIC_RELEASE = "semantic-release",
	STYLELINT = "stylelint",
	TYPESCRIPT = "typescript",
}
